# default configuration
baseURL = "http://timokrates.de"
languageCode = "en-us"
summaryLength = "10"
theme = "theme"
title = ""

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 1

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 2


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#001876"
#theme_color = "#16171B"
# contact info
phone = "+49 1522 34343490"
email = "timon.schelling@outlook.de"
address = "26135 Oldenburg, Germany"
# meta description
author = "Timon Schelling"
description = ""
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2020 by [Timon Schelling](https://timokrates.de)"


# preloader
[params.preloader]
enable = false
preloader = ""

# contact
[params.contact]
enable = false
form_action = ""

# google map
[params.map]
enable = false
gmap_api = ""
map_latitude = ""
map_longitude = ""
map_marker = ""

# social site
[[params.social]]
icon = "ti-github"
URL = "https://github.com/timon-schelling"

[[params.social]]
icon = "ti-instagram"
URL = "https://instagram.com/timokrates"
